### ISSUE TITLE
Export ChugSplashRegistry address in contracts repo

### ISSUE THREAD

**Issue by smartcontracts** [smartcontracts/chugsplash#7]
Original comment for context:

> We can probably consider exporting this in `@chugsplash/contracts` so the address automatically updates if we when we change the source during development

_Originally posted by @smartcontracts in https://github.com/smartcontracts/chugsplash/pull/4#discussion_r924974194_

---

The ChugSplashRegistry is being deployed via Create2. It should be easy to pre-compute the address of the ChugSplashRegistry and export it as a constant. This address will likely change a few times during the development process and it might be a headache to keep updating the constant everywhere. Once the contracts stabilize, we can add a simple CI check that asserts that the address has not changed between PRs.

**Comment by sam-goldman** [comment]
Closed by #61
